import type { Category, AlgoItem } from './types';

export const CATEGORIES: Category[] = [
  { id: 'sort', label: 'Sorting Algorithm' },
  { id: 'search', label: 'Search Algorithm' },
  { id: 'graph', label: 'Graph Algorithm' },
  { id: 'tree', label: 'Tree Structure' },
  { id: 'dp', label: 'Dynamic Programming' },
  { id: 'greedy', label: 'Greedy Algorithm' },
  { id: 'lds', label: 'Linear Data Structure' },
  { id: 'hash', label: 'Hash-Based Structure' },
  { id: 'heap', label: 'Heap / Priority Queue' },
  { id: 'dac', label: 'Divide & Conquer' },
  { id: 'back', label: 'Backtracking' },
  { id: 'string', label: 'String Algorithm' },
];

export const ITEMS: AlgoItem[] = [
  { sym: 'Bub', name: 'Bubble Sort', cat: 'sort', time: 'O(n\u00B2)', space: 'O(1)', desc: 'Repeatedly swaps adjacent out-of-order elements until the list is sorted.' },
  { sym: 'Sel', name: 'Selection Sort', cat: 'sort', time: 'O(n\u00B2)', space: 'O(1)', desc: 'Repeatedly selects the minimum remaining element and moves it into place.' },
  { sym: 'Ins', name: 'Insertion Sort', cat: 'sort', time: 'O(n\u00B2)', space: 'O(1)', desc: 'Builds a sorted prefix by inserting each new element into its correct position.' },
  { sym: 'Shl', name: 'Shell Sort', cat: 'sort', time: 'O(n log\u00B2n)', space: 'O(1)', desc: 'Generalizes insertion sort by comparing elements at decreasing gaps.' },
  { sym: 'Mrg', name: 'Merge Sort', cat: 'sort', time: 'O(n log n)', space: 'O(n)', desc: 'Recursively splits the list, sorts each half, then merges the sorted halves.' },
  { sym: 'Qck', name: 'Quick Sort', cat: 'sort', time: 'O(n log n)', space: 'O(log n)', desc: 'Partitions around a pivot and recursively sorts each side.' },
  { sym: 'Heq', name: 'Heap Sort', cat: 'sort', time: 'O(n log n)', space: 'O(1)', desc: 'Builds a max-heap then repeatedly extracts the maximum into place.' },
  { sym: 'Cnt', name: 'Counting Sort', cat: 'sort', time: 'O(n+k)', space: 'O(k)', desc: 'Counts occurrences of each value to sort integers in a known range.' },
  { sym: 'Rdx', name: 'Radix Sort', cat: 'sort', time: 'O(nk)', space: 'O(n+k)', desc: 'Sorts numbers digit by digit, from least to most significant.' },
  { sym: 'Tim', name: 'TimSort', cat: 'sort', time: 'O(n log n)', space: 'O(n)', desc: 'Hybrid of merge and insertion sort, used by Python and Java for general sorting.' },

  { sym: 'Lin', name: 'Linear Search', cat: 'search', time: 'O(n)', space: 'O(1)', desc: 'Checks each element in sequence until a match is found.' },
  { sym: 'Bin', name: 'Binary Search', cat: 'search', time: 'O(log n)', space: 'O(1)', desc: 'Repeatedly halves a sorted search range to find a target.' },
  { sym: 'Jmp', name: 'Jump Search', cat: 'search', time: 'O(\u221An)', space: 'O(1)', desc: 'Jumps ahead in fixed blocks, then scans linearly within the right block.' },
  { sym: 'Ipl', name: 'Interpolation Search', cat: 'search', time: 'O(log log n)', space: 'O(1)', desc: 'Estimates a likely position using value distribution before probing, for uniform data.' },
  { sym: 'Ext', name: 'Exponential Search', cat: 'search', time: 'O(log n)', space: 'O(1)', desc: 'Finds a range by doubling bounds, then binary searches within it.' },

  { sym: 'Bfs', name: 'Breadth-First Search', cat: 'graph', time: 'O(V+E)', space: 'O(V)', desc: 'Explores a graph level by level using a queue.' },
  { sym: 'Dfs', name: 'Depth-First Search', cat: 'graph', time: 'O(V+E)', space: 'O(V)', desc: 'Explores as far as possible along each branch before backtracking.' },
  { sym: 'Dij', name: 'Dijkstra\u2019s', cat: 'graph', time: 'O(E log V)', space: 'O(V)', desc: 'Finds shortest paths from a source in graphs with non-negative weights.' },
  { sym: 'Bfd', name: 'Bellman-Ford', cat: 'graph', time: 'O(VE)', space: 'O(V)', desc: 'Finds shortest paths and detects negative cycles, handles negative weights.' },
  { sym: 'Fwl', name: 'Floyd-Warshall', cat: 'graph', time: 'O(V\u00B3)', space: 'O(V\u00B2)', desc: 'Computes shortest paths between all pairs of vertices.' },
  { sym: 'Krk', name: 'Kruskal\u2019s', cat: 'graph', time: 'O(E log E)', space: 'O(V)', desc: 'Builds a minimum spanning tree by adding the cheapest edges that avoid cycles.' },
  { sym: 'Prm', name: 'Prim\u2019s', cat: 'graph', time: 'O(E log V)', space: 'O(V)', desc: 'Grows a minimum spanning tree one vertex at a time from a start node.' },
  { sym: 'Tpo', name: 'Topological Sort', cat: 'graph', time: 'O(V+E)', space: 'O(V)', desc: 'Orders nodes of a DAG so every edge points forward.' },
  { sym: 'Tar', name: 'Tarjan\u2019s SCC', cat: 'graph', time: 'O(V+E)', space: 'O(V)', desc: 'Finds strongly connected components in a single DFS pass.' },
  { sym: 'A*', name: 'A* Search', cat: 'graph', time: 'O(E)', space: 'O(V)', desc: 'Pathfinding that combines actual cost with a heuristic estimate to the goal.' },

  { sym: 'Bst', name: 'Binary Search Tree', cat: 'tree', time: 'O(log n)*', space: 'O(n)', desc: 'Keeps left children smaller and right children larger for fast lookup.' },
  { sym: 'Avl', name: 'AVL Tree', cat: 'tree', time: 'O(log n)', space: 'O(n)', desc: 'Self-balancing BST that rotates to keep subtree heights close.' },
  { sym: 'Rbt', name: 'Red-Black Tree', cat: 'tree', time: 'O(log n)', space: 'O(n)', desc: 'Self-balancing BST using color rules to bound tree height.' },
  { sym: 'Bpt', name: 'B-Tree', cat: 'tree', time: 'O(log n)', space: 'O(n)', desc: 'Balanced multi-way tree optimized for disk and database storage.' },
  { sym: 'Trc', name: 'Trie', cat: 'tree', time: 'O(L)', space: 'O(n\u00B7L)', desc: 'Tree of characters used for fast prefix lookup, as in autocomplete.' },
  { sym: 'Sgt', name: 'Segment Tree', cat: 'tree', time: 'O(log n)', space: 'O(n)', desc: 'Answers range queries (sum, min, max) and supports range updates.' },
  { sym: 'Fwt', name: 'Fenwick Tree', cat: 'tree', time: 'O(log n)', space: 'O(n)', desc: 'Compact structure for prefix sums with point updates, also called a BIT.' },

  { sym: 'Fib', name: 'Fibonacci (memo)', cat: 'dp', time: 'O(n)', space: 'O(n)', desc: 'Caches subproblem results to avoid recomputing overlapping calls.' },
  { sym: 'Knp', name: '0/1 Knapsack', cat: 'dp', time: 'O(nW)', space: 'O(nW)', desc: 'Chooses items under a weight limit to maximize value, no fractional picks.' },
  { sym: 'Lcs', name: 'Longest Common Subsequence', cat: 'dp', time: 'O(mn)', space: 'O(mn)', desc: 'Finds the longest subsequence shared by two sequences.' },
  { sym: 'Lis', name: 'Longest Increasing Subsequence', cat: 'dp', time: 'O(n log n)', space: 'O(n)', desc: 'Finds the longest strictly increasing subsequence of a sequence.' },
  { sym: 'Edt', name: 'Edit Distance', cat: 'dp', time: 'O(mn)', space: 'O(mn)', desc: 'Minimum insertions, deletions, and substitutions to turn one string into another.' },
  { sym: 'Mcm', name: 'Matrix Chain Mult.', cat: 'dp', time: 'O(n\u00B3)', space: 'O(n\u00B2)', desc: 'Finds the cheapest order to multiply a chain of matrices.' },
  { sym: 'Cch', name: 'Coin Change', cat: 'dp', time: 'O(n\u00B7amt)', space: 'O(amt)', desc: 'Finds the minimum number of coins that sum to a target amount.' },

  { sym: 'Huf', name: 'Huffman Coding', cat: 'greedy', time: 'O(n log n)', space: 'O(n)', desc: 'Builds an optimal prefix code by repeatedly merging the lowest-frequency nodes.' },
  { sym: 'Act', name: 'Activity Selection', cat: 'greedy', time: 'O(n log n)', space: 'O(n)', desc: 'Picks the maximum set of non-overlapping intervals by earliest finish time.' },
  { sym: 'Job', name: 'Job Scheduling', cat: 'greedy', time: 'O(n log n)', space: 'O(n)', desc: 'Orders jobs by deadline or profit to maximize scheduled value.' },

  { sym: 'Arr', name: 'Array', cat: 'lds', time: 'O(1) access', space: 'O(n)', desc: 'Fixed-size contiguous block offering constant-time indexed access.' },
  { sym: 'Lkl', name: 'Linked List', cat: 'lds', time: 'O(n) access', space: 'O(n)', desc: 'Chain of nodes linked by pointers, with cheap insertion and removal.' },
  { sym: 'Stk', name: 'Stack', cat: 'lds', time: 'O(1) push/pop', space: 'O(n)', desc: 'Last-in-first-out structure used for undo, recursion, and parsing.' },
  { sym: 'Que', name: 'Queue', cat: 'lds', time: 'O(1) enqueue/dequeue', space: 'O(n)', desc: 'First-in-first-out structure used for scheduling and BFS.' },
  { sym: 'Dql', name: 'Deque', cat: 'lds', time: 'O(1) both ends', space: 'O(n)', desc: 'Double-ended queue allowing fast insertion and removal at both ends.' },

  { sym: 'Has', name: 'Hash Table', cat: 'hash', time: 'O(1)*', space: 'O(n)', desc: 'Maps keys to buckets via a hash function for near-constant lookup.' },
  { sym: 'Blf', name: 'Bloom Filter', cat: 'hash', time: 'O(k)', space: 'O(m)', desc: 'Probabilistic structure that tests set membership with no false negatives.' },
  { sym: 'Lru', name: 'LRU Cache', cat: 'hash', time: 'O(1)', space: 'O(n)', desc: 'Hash map plus linked list that evicts the least recently used entry.' },
  { sym: 'Bhp', name: 'Binary Heap', cat: 'heap', time: 'O(log n)', space: 'O(n)', desc: 'Array-backed tree giving fast access to the min or max element.' },
  { sym: 'Fhp', name: 'Fibonacci Heap', cat: 'heap', time: 'O(1) amortized', space: 'O(n)', desc: 'Heap variant with very fast amortized decrease-key, used in advanced Dijkstra.' },

  { sym: 'Kar', name: 'Karatsuba Mult.', cat: 'dac', time: 'O(n^1.58)', space: 'O(n)', desc: 'Multiplies large numbers faster than the grade-school method via recursion.' },
  { sym: 'Cls', name: 'Closest Pair of Points', cat: 'dac', time: 'O(n log n)', space: 'O(n)', desc: 'Finds the nearest two points by recursively dividing the plane.' },
  { sym: 'Nqn', name: 'N-Queens', cat: 'back', time: 'O(n!)', space: 'O(n)', desc: 'Places n queens on a board with none attacking another, via trial and backtrack.' },
  { sym: 'Sud', name: 'Sudoku Solver', cat: 'back', time: 'O(9^m)', space: 'O(1)', desc: 'Fills a grid by trying digits and backtracking on contradictions.' },
  { sym: 'Kmp', name: 'Knuth-Morris-Pratt', cat: 'string', time: 'O(n+m)', space: 'O(m)', desc: 'Finds a pattern in text in linear time using a precomputed prefix table.' },
  { sym: 'Rbk', name: 'Rabin-Karp', cat: 'string', time: 'O(n+m)', space: 'O(1)', desc: 'Finds a pattern using rolling hashes for fast candidate matching.' },
  { sym: 'Sfx', name: 'Suffix Array', cat: 'string', time: 'O(n log n)', space: 'O(n)', desc: 'Sorted array of all suffixes, enabling fast substring queries.' },
];
